(()=>{const $=q=>document.querySelector(q),stage=$("#stage"),tracks=$("#tracks");let S={duration:10,time:0,aspect:"9:16",items:[],selected:null,undo:[],redo:[],playing:false},drag=null,last=0,raf;const id=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2),cp=o=>JSON.parse(JSON.stringify(o)),item=()=>S.items.find(x=>x.id===S.selected);
function snap(){S.undo.push(JSON.stringify({duration:S.duration,aspect:S.aspect,items:S.items}));if(S.undo.length>50)S.undo.shift();S.redo=[]}function save(){localStorage.setItem("pb-v01",JSON.stringify({duration:S.duration,aspect:S.aspect,items:S.items}));$("#save").textContent="保存済";setTimeout(()=>$("#save").textContent="保存",500)}
function load(){try{let d=JSON.parse(localStorage.getItem("pb-v01"));if(d)Object.assign(S,d)}catch{}}function fmt(t){let m=Math.floor(t/60),s=t%60;return String(m).padStart(2,"0")+":"+s.toFixed(2).padStart(5,"0")}
function aspect(){let[a,b]=S.aspect.split(":").map(Number);stage.style.aspectRatio=a+"/"+b;if(innerWidth>innerHeight){stage.style.height="min(62vh,calc(100vw * .44))";stage.style.width="auto"}else{stage.style.height="auto";stage.style.width=`min(${a/b*75}vh,92vw)`}$("#aspect").textContent=S.aspect}
function render(){aspect();stage.querySelectorAll(".pip").forEach(e=>e.remove());tracks.innerHTML="";S.items.forEach((x,z)=>{let e=document.createElement("div");e.className="pip "+(x.type==="text"?"txt ":"")+(x.id===S.selected?"sel":"");e.dataset.id=x.id;e.style.cssText=`width:${x.w}px;height:${x.h}px;transform:translate(${x.x}px,${x.y}px) rotate(${x.r}deg);opacity:${x.o/100};z-index:${z+1};display:${S.time>=x.start&&S.time<=x.end?"":"none"}`;if(x.type==="image"){let im=new Image;im.src=x.src;e.append(im)}else e.textContent=x.text;stage.append(e);let tr=document.createElement("div");tr.className="track";let c=document.createElement("div");c.className="clip "+(x.id===S.selected?"sel":"");c.dataset.id=x.id;c.style.left=x.start/S.duration*100+"%";c.style.width=(x.end-x.start)/S.duration*100+"%";c.textContent=x.name;tr.append(c);tracks.append(tr)});$("#seek").max=S.duration;$("#seek").value=S.time;$("#duration").value=S.duration;$("#clock").textContent=fmt(S.time)+" / "+fmt(S.duration);inspect()}
function select(v){S.selected=v;render();$("#inspector").hidden=!v}function inspect(){let x=item();if(!x)return;$("#iname").textContent=x.name;[["ix","x"],["iy","y"],["iw","w"],["ih","h"],["ir","r"],["io","o"],["is","start"],["ie","end"]].forEach(([a,b])=>$("#"+a).value=Math.round(x[b]*100)/100)}
$("#files").onchange=e=>{let fs=[...e.target.files];if(!fs.length)return;snap();Promise.all(fs.map(f=>new Promise(ok=>{let r=new FileReader;r.onload=()=>{let w=stage.clientWidth,h=stage.clientHeight,s=Math.min(w,h)*.32,n={id:id(),type:"image",name:f.name,src:r.result,x:w/2-s/2,y:h/2-s/2,w:s,h:s,r:0,o:100,start:0,end:S.duration};S.items.push(n);S.selected=n.id;ok()};r.readAsDataURL(f)}))).then(()=>{render();save()});e.target.value=""}
$("#text").onclick=()=>{let t=prompt("文字を入力","TEXT");if(t==null)return;snap();let w=stage.clientWidth,h=stage.clientHeight,n={id:id(),type:"text",name:t,text:t,x:w*.25,y:h*.45,w:w*.5,h:55,r:0,o:100,start:0,end:S.duration};S.items.push(n);S.selected=n.id;render();save()}
stage.onpointerdown=e=>{let el=e.target.closest(".pip");if(!el){select(null);return}select(el.dataset.id);let x=item();snap();el.setPointerCapture(e.pointerId);drag={p:e.pointerId,cx:e.clientX,cy:e.clientY,x:x.x,y:x.y}}
stage.onpointermove=e=>{if(!drag||drag.p!==e.pointerId)return;let x=item(),nx=drag.x+e.clientX-drag.cx,ny=drag.y+e.clientY-drag.cy,sw=stage.clientWidth,sh=stage.clientHeight,t=8,gx=false,gy=false,cx=nx+x.w/2,cy=ny+x.h/2;if(Math.abs(cx-sw/2)<t){nx=sw/2-x.w/2;gx=true}if(Math.abs(cy-sh/2)<t){ny=sh/2-x.h/2;gy=true}for(let o of S.items)if(o.id!==x.id){let ox=o.x+o.w/2,oy=o.y+o.h/2;if(Math.abs(cx-ox)<t){nx=ox-x.w/2;gx=true}if(Math.abs(cy-oy)<t){ny=oy-x.h/2;gy=true}}x.x=nx;x.y=ny;render();$("#gv").style.display=gx?"block":"none";$("#gh").style.display=gy?"block":"none"}
stage.onpointerup=()=>{drag=null;$("#gv").style.display=$("#gh").style.display="none";save()};tracks.onclick=e=>{let c=e.target.closest(".clip");if(c)select(c.dataset.id)}
;[["ix","x"],["iy","y"],["iw","w"],["ih","h"],["ir","r"],["io","o"],["is","start"],["ie","end"]].forEach(([a,b])=>$("#"+a).onchange=e=>{let x=item();if(!x)return;snap();x[b]=Number(e.target.value);if(b==="start")x.start=Math.max(0,Math.min(x.start,x.end));if(b==="end")x.end=Math.min(S.duration,Math.max(x.start,x.end));render();save()})
$("#center").onclick=()=>{let x=item();if(!x)return;snap();x.x=(stage.clientWidth-x.w)/2;x.y=(stage.clientHeight-x.h)/2;render();save()};$("#fit").onclick=()=>{let x=item();if(!x)return;snap();let k=Math.min(stage.clientWidth/x.w,stage.clientHeight/x.h)*.8;x.w*=k;x.h*=k;x.x=(stage.clientWidth-x.w)/2;x.y=(stage.clientHeight-x.h)/2;render();save()}
$("#front").onclick=()=>{let i=S.items.findIndex(x=>x.id===S.selected);if(i<0)return;snap();S.items.push(S.items.splice(i,1)[0]);render();save()};$("#back").onclick=()=>{let i=S.items.findIndex(x=>x.id===S.selected);if(i<0)return;snap();S.items.unshift(S.items.splice(i,1)[0]);render();save()}
$("#dup").onclick=()=>{let x=item();if(!x)return;snap();let n=cp(x);n.id=id();n.name+=" copy";n.x+=15;n.y+=15;S.items.push(n);S.selected=n.id;render();save()};$("#del").onclick=()=>{let i=S.items.findIndex(x=>x.id===S.selected);if(i<0)return;snap();S.items.splice(i,1);S.selected=null;render();save()};$("#close").onclick=()=>select(null)
$("#aspect").onclick=()=>{snap();S.aspect=S.aspect==="9:16"?"16:9":"9:16";requestAnimationFrame(render);save()};$("#duration").onchange=e=>{snap();S.duration=Math.max(1,+e.target.value||10);S.items.forEach(x=>x.end=Math.min(x.end,S.duration));S.time=Math.min(S.time,S.duration);render();save()};$("#seek").oninput=e=>{S.time=+e.target.value;render()}
function tick(t){if(!S.playing)return;if(!last)last=t;S.time+=(t-last)/1000;last=t;if(S.time>=S.duration){S.time=0;S.playing=false;$("#play").textContent="▶︎";render();return}render();raf=requestAnimationFrame(tick)}$("#play").onclick=()=>{S.playing=!S.playing;$("#play").textContent=S.playing?"⏸":"▶︎";last=0;if(S.playing)raf=requestAnimationFrame(tick);else cancelAnimationFrame(raf)}
$("#save").onclick=save;$("#undo").onclick=()=>{if(!S.undo.length)return;S.redo.push(JSON.stringify({duration:S.duration,aspect:S.aspect,items:S.items}));Object.assign(S,JSON.parse(S.undo.pop()));S.selected=null;render();save()};$("#redo").onclick=()=>{if(!S.redo.length)return;S.undo.push(JSON.stringify({duration:S.duration,aspect:S.aspect,items:S.items}));Object.assign(S,JSON.parse(S.redo.pop()));S.selected=null;render();save()};addEventListener("resize",()=>requestAnimationFrame(render));load();requestAnimationFrame(render)})();
